name = "train"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "everydaytongji-assets"
